export const CATEGORIES = [
    'todos',
    'INFORMATICA',
    'ELECTRONICA',
    'CONTADURIA',
    'ADMINISTRACION',
    'ELECTRICIDAD',
    'MECANICA',
    'INSTRUMENTACION',
    'TELECOMUNICACIONES',
]